config/routes.rb
Portal::Application.routes.draw do
  resources :newspapers

  resources :events

  resources :news

  resources :areas

  resources :subdivisions

  resources :enterprises

   root 'news#index'

  

end

app/models/subdivision.rb
class Subdivision < ActiveRecord::Base
end

app/controllers/subdivisions_controller.rb
class SubdivisionsController < ApplicationController
  before_action :set_subdivision, only: [:show, :edit, :update, :destroy]

  # GET /subdivisions
  # GET /subdivisions.json
  def index
    @subdivisions = Subdivision.all
  end

  # GET /subdivisions/1
  # GET /subdivisions/1.json
  def show
  end

  # GET /subdivisions/new
  def new
    @subdivision = Subdivision.new
  end

  # GET /subdivisions/1/edit
  def edit
  end

  # POST /subdivisions
  # POST /subdivisions.json
  def create
    @subdivision = Subdivision.new(subdivision_params)

    respond_to do |format|
      if @subdivision.save
        format.html { redirect_to @subdivision, notice: 'Subdivision was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subdivision }
      else
        format.html { render action: 'new' }
        format.json { render json: @subdivision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subdivisions/1
  # PATCH/PUT /subdivisions/1.json
  def update
    respond_to do |format|
      if @subdivision.update(subdivision_params)
        format.html { redirect_to @subdivision, notice: 'Subdivision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subdivision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subdivisions/1
  # DELETE /subdivisions/1.json
  def destroy
    @subdivision.destroy
    respond_to do |format|
      format.html { redirect_to subdivisions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subdivision
      @subdivision = Subdivision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subdivision_params
      params.require(:subdivision).permit(:number, :name)
    end
end

app/helpers/subdivisions_helper.rb
module SubdivisionsHelper
end

app/views/subdivisions/_form.html.haml
= form_for @subdivision do |f|
  - if @subdivision.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subdivision.errors.count, "error")} prohibited this subdivision from being saved:"
      %ul
        - @subdivision.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/subdivisions/edit.html.haml
%h1 Editing subdivision

= render 'form'

= link_to 'Show', @subdivision
\|
= link_to 'Back', subdivisions_path

app/views/subdivisions/index.html.haml
%h1 Listing subdivisions

%table
  %tr
    %th Number
    %th Name
    %th
    %th
    %th

  - @subdivisions.each do |subdivision|
    %tr
      %td= subdivision.number
      %td= subdivision.name
      %td= link_to 'Show', subdivision
      %td= link_to 'Edit', edit_subdivision_path(subdivision)
      %td= link_to 'Destroy', subdivision, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subdivision', new_subdivision_path

app/views/subdivisions/new.html.haml
%h1 New subdivision

= render 'form'

= link_to 'Back', subdivisions_path

app/views/subdivisions/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @subdivision.number
%p
  %b Name:
  = @subdivision.name

= link_to 'Edit', edit_subdivision_path(@subdivision)
\|
= link_to 'Back', subdivisions_path