config/routes.rb
Portal::Application.routes.draw do
  resources :newspapers

  resources :events

  resources :news

  resources :areas

  resources :subdivisions

  resources :enterprises

   root 'news#index'

  

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    @news.date=Time.now
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:date, :title, :text)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.haml
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      %ul
        - @news.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/news/edit.html.haml
- model_class = News
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/news/index.html.haml
%h1 Новости
.page-header
  - @news.each do |news|
    %h1= news.title
    .time= l news.date,:format=>:long
    %rp= news.text
    %h2=link_to 'Подробнее', news
    %td= link_to 'Редактировать', edit_news_path(news)
    \|
    %td= link_to 'Удалить', news, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'Добавить новость', new_news_path

app/views/news/new.html.haml
%h1 Добавление новости

= render 'form'

= link_to 'К списку новостей', news_index_path

app/views/news/show.html.haml
- model_class = News
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:date) + ':'
  %br
  = @news.date
%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @news.title
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = @news.text

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), news_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_news_path(@news), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), news_path(@news), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'