config/routes.rb
Portal::Application.routes.draw do
  resources :newspapers

  resources :events

  resources :news

  resources :areas

  resources :subdivisions

  resources :enterprises

   root 'news#index'

  

end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :set_newspaper, only: [:show, :edit, :update, :destroy]

  # GET /newspapers
  # GET /newspapers.json
  def index
    @newspapers = Newspaper.all
  end

  # GET /newspapers/1
  # GET /newspapers/1.json
  def show
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers
  # POST /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully created.' }
        format.json { render action: 'show', status: :created, location: @newspaper }
      else
        format.html { render action: 'new' }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1
  # PATCH/PUT /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1
  # DELETE /newspapers/1.json
  def destroy
    @newspaper.destroy
    respond_to do |format|
      format.html { redirect_to newspapers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newspaper_params
      params.require(:newspaper).permit(:year, :number, :relese_date)
    end
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/newspapers/_form.html.haml
= form_for @newspaper do |f|
  - if @newspaper.errors.any?
    #error_explanation
      %h2= "#{pluralize(@newspaper.errors.count, "error")} prohibited this newspaper from being saved:"
      %ul
        - @newspaper.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :relese_date
    = f.datetime_select :relese_date
  .actions
    = f.submit 'Save'

app/views/newspapers/edit.html.haml
%h1 Editing newspaper

= render 'form'

= link_to 'Show', @newspaper
\|
= link_to 'Back', newspapers_path

app/views/newspapers/index.html.haml
%h1 Listing newspapers

%table
  %tr
    %th Year
    %th Number
    %th Relese date
    %th
    %th
    %th

  - @newspapers.each do |newspaper|
    %tr
      %td= newspaper.year
      %td= newspaper.number
      %td= newspaper.relese_date
      %td= link_to 'Show', newspaper
      %td= link_to 'Edit', edit_newspaper_path(newspaper)
      %td= link_to 'Destroy', newspaper, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Newspaper', new_newspaper_path

app/views/newspapers/new.html.haml
%h1 New newspaper

= render 'form'

= link_to 'Back', newspapers_path

app/views/newspapers/show.html.haml
%p#notice= notice

%p
  %b Year:
  = @newspaper.year
%p
  %b Number:
  = @newspaper.number
%p
  %b Relese date:
  = @newspaper.relese_date

= link_to 'Edit', edit_newspaper_path(@newspaper)
\|
= link_to 'Back', newspapers_path